name: code_quality

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/code_quality.yml"
      - "doltcli/**"
      - "scripts/**"
      - "tests/**"
      - "requirements/development.txt"
      - "pyproject.toml"

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
          cache: 'pip'
          cache-dependency-path: "**/requirements/development.txt"

      - name: Run black checks
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/development.txt
          black --check --diff --color .

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
          cache: 'pip'
          cache-dependency-path: "**/requirements/development.txt"

      - name: Run isort checks
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/development.txt
          isort --check --diff --color .

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
          cache: 'pip'
          cache-dependency-path: "**/requirements/development.txt"

      - name: Run flake8 checks
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/development.txt
          flake8 .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: "3.10"
          architecture: x64
          cache: 'pip'
          cache-dependency-path: "**/requirements/development.txt"

      - name: Run mypy
        run: |
          python -m pip install -r requirements/development.txt
          mkdir -p .mypy_cache
          mypy doltcli --config-file pyproject.toml
