name: unit_tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/code_quality.yml"
      - "doltcli/**"
      - "scripts/**"
      - "tests/**"
      - "requirements/development.txt"
      - "pyproject.toml"

jobs:
  unit_tests:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo curl -L https://github.com/liquidata-inc/dolt/releases/v0.52.0/download/install.sh | sudo bash
          dolt config --global --add user.email bojack@horseman.com
          dolt config --global --add user.name "Bojack Horseman"
          dolt config --global --add metrics.host eventsapi.awsdev.ld-corp.com
          dolt config --global --add metrics.port 443
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
      - name: Run tests
        run: pytest -v tests --cov=doltcli --cov-report=term --cov-report xml